name: Package PokeArtDex Stock Addon

on: workflow_dispatch

env:
  PACKAGE_NAME: "PokeArtDex-Stock-Addon"
  SUB_FOLDER: "pokeartdex-stock-addon/"

jobs:
  upload-stock-addon:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # needed for finding tag
        with:
          fetch-depth: 0

      - name: Copy icon to sub folder
        run: cp icons/icon.svg ${{ env.SUB_FOLDER }}

      - name: Zip folder
        run: zip -r ${{ env.PACKAGE_NAME }}.zip ${{ env.SUB_FOLDER }}

      - name: Get latest tag
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Upload addon to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          files: "${{ env.PACKAGE_NAME }}.zip"
